- job:
    name: rousette-f38-clang-asan-ubsan
    parent: f38-clang-asan-ubsan
    requires: CzechLight-deps-f38-clang-asan-ubsan
    required-projects: &projects
      - CzechLight/dependencies
      - name: github/nghttp2/nghttp2-asio
        override-checkout: main
    vars:
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/rousette'].src_dir }}"

- project:
    check:
      jobs:
        - f38-gcc-cover:
            requires: CzechLight-deps-f38-gcc
            required-projects: *projects
        - rousette-f38-clang-asan-ubsan
        - f38-clang-tsan:
            requires: CzechLight-deps-f38-clang-tsan
            required-projects: *projects
        - f38-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f38-gcc-cover-previous:
            requires: CzechLight-deps-f38-gcc
            required-projects: *projects
        - czechlight-clearfog:
            required-projects:
              - CzechLight/br2-external
            requires: CzechLight-br2-build-clearfog
