- hosts: all
  tasks:
    - name: install nghttp2
      package:
        name: libnghttp2-devel
        state: present
      become: true

    - name: install pam_wrapper
      package:
        name: pam_wrapper
        state: present
      become: true

    - name: install docopt-cpp
      package:
        name: docopt-cpp-devel
        state: present
      become: true
