- hosts: all
  tasks:
    - name: install libnghttp2 with ASIO
      shell: |
        CI_PARALLEL_JOBS=$(awk -vcpu=$(getconf _NPROCESSORS_ONLN) 'BEGIN{printf "%.0f", cpu*1.3+1}')
        cd {{ ansible_user_dir }}/src/github/nghttp2/nghttp2/
        autoreconf -i
        automake
        autoconf
        ./configure \
          --prefix={{ ansible_user_dir }}/target \
          --enable-asio-lib \
          --enable-app
        make -j$CI_PARALLEL_JOBS
        make -j$CI_PARALLEL_JOBS install
