- hosts: all
  tasks:
    - name: install nghttp2
      package:
        name: libnghttp2-devel
        state: present
      become: true

    - name: install libdb-utils
      package:
        name: libdb-utils
        state: present
      become: true
